### ISSUE TITLE
Proposal: Undeleted_at

### ISSUE THREAD

**Issue by progmancod** [flipbit03/sqlalchemy-easy-softdelete#20]
For auditing purposes, it would be important to fill in the 'undeleted_at' column as well.

**Comment by flipbit03** [comment]
Hello, @progmancod! Thank you for the suggestion :pray: but I believe providing such field in the model itself would be somewhat lacking, as we would only be able to store the "most recent" undeletion, which is suboptimal/lacking for auditing purposes. 

If a single undeletion timestamp store is okay for your current use case, then I guess this approach is fine, but I think baking in any auditing or "entity state audit/logging" assumption in the library itself would end up setting a standard that some people might not agree with. It'd accidentally stunt the ability for people to choose which approach they want, or even to leave auditing out completely - the default case.

Imo, a library should do one thing and do it well, which is to make working with soft-deleted entities a breeze. Trying to embrace too much hurts composability in the long run.

Have a good one!
