### ISSUE TITLE
Issue with Soft Delete when using Recursive CTEs

### ISSUE THREAD

**Issue by amirhossein828** [flipbit03/sqlalchemy-easy-softdelete#21]
Hello,

I've encountered a problem when using sqlalchemy_easy_softdelete with recursive Common Table Expressions (CTEs) in SQLAlchemy.

Environment:

SQLAlchemy version: "^2.0.14"
sqlalchemy_easy_softdelete version:"^0.7.1"
Python version:"^3.10"
Steps to Reproduce:

Define a model with soft deletion enabled.
Implement a recursive CTE query on this model.
Try to execute the query.
Expected Behavior:
The query should execute without errors and should not return the soft-deleted records.

Actual Behavior:
I received a NotImplementedError with the message: "Unsupported object <class 'sqlalchemy.sql.selectable.CTE'> in statement.froms".

Additional Details:
It appears the library currently doesn't support CTEs, specifically when they are used in the FROM clause of a SELECT statement.

It would be great if support for CTEs could be added, or at least a mechanism to bypass soft delete for specific queries when using recursive CTEs or other advanced SQLAlchemy features.

Thank you for your attention to this issue!

**Comment by flipbit03** [comment]
Hello @amirhossein828, thanks for reaching out! I have never used CTEs in SQLAlchemy and as such, I have not implemented support for them. 

Can you paste more details and possibly some sample "query" and "model" code? I am developing this library using TDD, so I'd like to create a failing test with your model + query (or something similar that evokes the exception) and then we can attempt to develop support for it. Having a specific query/model combo which fails would be of huge help for building the solution.

Thanks in advance!

**Comment by flipbit03** [comment]
Stale issue without further interaction
