### ISSUE TITLE
Soft Delete on queries with offset and limit works incorrect

### ISSUE THREAD

**Issue by stepanlevel** [flipbit03/sqlalchemy-easy-softdelete#24]
* SQLAlchemy Easy Soft-Delete version: 0.8.2
* Python version: 3.11.5
* Operating System: MacOS

### Description

Attempting to use SoftDelete on queries with limit and offset. 
When I use limit or (and) offset with a simple query, the query returns soft-deleted items too.
Looks like limit and offset override the query. 

Example:
```
db.query(Account).all() - works fine
db.query(Account).limit(100).offset(0) - return all acounts with deleted accounts
```

**Comment by radzki** [comment]
@stepanlevel I was unable to reproduce your issue. I tested it locally in `tests` and also tried it in an external project using the lib. The only difference is that I've used Python 3.11.8 and Ubuntu, but I assume they don't make much of a difference.

**Comment by flipbit03** [comment]
Closing as this stale and not reproducible. Thanks @radzki for testing!
