### ISSUE TITLE
Python 3.9 compatibility ?

### ISSUE THREAD

**Issue by frco9** [flipbit03/sqlalchemy-easy-softdelete#5]
* SQLAlchemy Easy Soft-Delete version: 0.4.0
* Python version: 3.9
* Operating System: Mac OS

### Description

Why only supporting python 3.10 and not 3.9 ? We're using AWS Lambda which has not released yet python 3.10 so we're stuck with python 3.9. I'm considering forking this to support python 3.9, is any there strong incompatibility ?

**Comment by flipbit03** [comment]
Adding support for Python 3.9 should be trivial. The only major hard dependency is actually **SQLAlchemy v1.4**.

If you can provide a pull request and implement testing with 3.9 (possibly via Docker, since that's how we test on CI/CD), we can merge it in!

**Comment by flipbit03** [comment]
@frco9 I've updated the library to support Python 3.9 and also SQLAlchemy 2.0. Make sure to check it out.
